#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$1" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -i -tags k8s -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/agent ./pkg/agent
